services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

